from __future__ import annotations

from pathlib import Path

from .models import InstanceRecord


def generate_compose(project_dir: Path, instances: list[InstanceRecord]) -> str:
    lines = [
        "# This file is generated by frpc WebUI. Do not edit by hand.",
        "services:",
    ]

    enabled_instances = [instance for instance in instances if instance.enabled]
    if not enabled_instances:
        lines.append("  {}")
    else:
        for instance in enabled_instances:
            service_name = f"frpc-{instance.name}"
            config_mount = f"./instances/{instance.name}/frpc.toml:/etc/frp/frpc.toml:ro"
            lines.extend(
                [
                    f"  {service_name}:",
                    "    image: ${FRP_IMAGE:-ghcr.io/fatedier/frpc:v0.68.1}",
                    "    restart: unless-stopped",
                    "    mem_limit: ${FRPC_MEMORY_LIMIT:-128m}",
                    '    cpus: "${FRPC_CPU_LIMIT:-0.25}"',
                    "    read_only: true",
                    "    init: true",
                    "    cap_drop:",
                    "      - ALL",
                    "    security_opt:",
                    "      - no-new-privileges:true",
                    "    tmpfs:",
                    "      - /tmp:size=16m,mode=1777",
                    "    extra_hosts:",
                    '      - "host.docker.internal:host-gateway"',
                    "    environment:",
                    "      TZ: ${TZ:-Asia/Shanghai}",
                    "    networks:",
                    "      - frpc-outbound",
                    "    logging:",
                    "      driver: json-file",
                    "      options:",
                    '        max-size: "10m"',
                    '        max-file: "3"',
                    f"    container_name: {service_name}",
                    '    command: ["-c", "/etc/frp/frpc.toml"]',
                    "    volumes:",
                    f"      - {config_mount}",
                    "",
                ]
            )

    lines.extend(
        [
            "",
            "networks:",
            "  frpc-outbound:",
            "    driver: bridge",
        ]
    )
    return "\n".join(lines)


def write_generated_compose(project_dir: Path, instances: list[InstanceRecord]) -> Path:
    path = Path(project_dir) / "compose.generated.yaml"
    path.write_text(generate_compose(Path(project_dir), instances), encoding="utf-8")
    return path
